print('같은 경로상')
print('import mymod')
print('from mymod import a,b')
print('from mod import *')
print('다른 경로상(sys 사용)')
print('import sys\nsys.path.append')
print('# from ./mymod/모듈명 import *')
print('sys.path.append('".\\mymod"')')
print('sys.path.append(''./mymod'')')
print("sys.path.append('mymod')")